### PR TITLE
fix: add workaround for older istio-pilot upgrades

### LINKED ISSUE #204: istio-pilot v1.12, v1.13, and v1.14 deploy incorrect ValidatingWebhookConfiguration during upgrade
`istioctl` v1.12, 1.13, and 1.14 have a bug where `istioctl upgrade` incorrectly creates a `ValidatingWebhookConfiguration` called `istiod-default-validator` that looks for `istiod` (the webhook's workload) in the default `istio-system` namespace, not the namespace we deploy `istio-pilot` to set (typically `kubeflow`). This results in a failing webhook immediately after upgrading to any of these versions and 404 errors raised when handling the `config-changed` event. 

This does not affect upgrading to istio v1.15+.  To fix this, we could patch the misconfigured webhook configuration after upgrade

### PR DESCRIPTION
**Pull request by ca-scribner**
Adds a workaround for bug #204, where `istioctl upgrade` for istioctl versions 1.12/1.13/1.14 incorrectly create a webhook configuration pointing to the default `istio-system` namespace instead of our current namespace.  This fix patches the webhook configuration after doing `istioctl upgrade` in order to fix the problem.

With this fix, we can now upgrade from Istio 1.11 to Istio 1.12 (and through to 1.16, provided we build charms for each of the intermediate minor versions). 

Closes #204.

### Test instructions

Build this istio-pilot charm from this PR to create an istio-pilot charm with istioctl v1.16.2.  Then use this script to use that .charm file as template for istio-pilot charms with istioctl versions 1.12.9, 1.13.9, 1.14.6, 1.15.6, and 1.16.2:
```bash
TEMPLATE_CHARM=istio-pilot_ubuntu-20.04-amd64.charm
TEMP_CHARM=temp.charm

for version in 1.12.9 1.13.9 1.14.6 1.15.6 1.16.2; do
	echo Working on version $version

	# Get this istioctl
	wget https://github.com/istio/istio/releases/download/${version}/istioctl-${version}-linux-amd64.tar.gz
	tar -xvzf istioctl-${version}-linux-amd64.tar.gz
	rm istioctl-${version}-linux-amd64.tar.gz

	# Make a new packed charm, removing existing istioctl
	cp $TEMPLATE_CHARM $TEMP_CHARM
	zip $TEMP_CHARM istioctl -d

	# Inject istioctl into charm
	zip $TEMP_CHARM istioctl
	rm istioctl

	mv $TEMP_CHARM istio-pilot_ubuntu-20.04-amd64_istioctl_$version.charm
done
```

This should yield the following charm files:
* istio-pilot_ubuntu-20.04-amd64_istioctl_1.12.9.charm
* istio-pilot_ubuntu-20.04-amd64_istioctl_1.13.9.charm
* istio-pilot_ubuntu-20.04-amd64_istioctl_1.14.6.charm
* istio-pilot_ubuntu-20.04-amd64_istioctl_1.15.6.charm
* istio-pilot_ubuntu-20.04-amd64_istioctl_1.16.2.charm

Now test the upgrade procedure from Istio 1.11 to 1.16:

```
# Note: plenty of things are currently pointing to /edge and eventually they should be /stable

# Deploy and test istio 1.11 to confirm it is working.  Use the Kubeflow dashboard a test for the ingress
juju deploy istio-pilot --channel=1.11/stable --trust
juju deploy istio-gateway --channel=1.11/stable --trust --config kind=ingress istio-ingressgateway
juju relate istio-pilot istio-ingressgateway

juju deploy kubeflow-profiles --channel 1.7/edge --trust
juju deploy kubeflow-dashboard --channel 1.7/edge --trust

juju relate kubeflow-profiles kubeflow-dashboard
juju relate kubeflow-dashboard:ingress istio-pilot:ingress

# Once everything is green, check for VirtualService and Gateway objects
kubectl get vs  # Should see one for dashboard
kubectl get gateway  # Should see one

# Regenerate the gateway if needed
juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"

# test access dashboard
# # browse to 10.64.140.43.nip.io  # <-- should work

# Upgrade istio

# Remove istio-gateway to avoid upgrade issues (some older `istio update` will affect the ingress gateway workload)
juju remove-application istio-ingressgateway

# Upgrade (local files)
# Note:
# * between each upgrade you should be able to redeploy and use the istio-ingressgateway.  
# * make sure each refresh completes before starting the next one
juju refresh istio-pilot --path ./istio-pilot_ubuntu-20.04-amd64_istioctl_1.12.9.charm
juju refresh istio-pilot --path ./istio-pilot_ubuntu-20.04-amd64_istioctl_1.13.9.charm
juju refresh istio-pilot --path ./istio-pilot_ubuntu-20.04-amd64_istioctl_1.14.6.charm
juju refresh istio-pilot --path ./istio-pilot_ubuntu-20.04-amd64_istioctl_1.15.6.charm
juju refresh istio-pilot --path ./istio-pilot_ubuntu-20.04-amd64_istioctl_1.16.2.charm

# # Once this is in charmhub, above can be replaced with:
# juju refresh istio-pilot --channel 1.12/edge
# juju refresh istio-pilot --channel 1.13/edge
# juju refresh istio-pilot --channel 1.14/edge
# juju refresh istio-pilot --channel 1.15/edge
# juju refresh istio-pilot --channel 1.16/edge

# Now redeploy istio-gateway and see if it works again
juju deploy istio-gateway --channel=1.16/edge --trust --config kind=ingress istio-ingressgateway
juju relate istio-pilot istio-ingressgateway

# test access dashboard
# # browse to 10.64.140.43.nip.io  # <-- should work
```

### CODE REVIEW

**Comment by ca-scribner** [comment]
What I've tested so far:

* (the instructions in the PR description) deploy istio 1.11, remove istio-gateway, refresh through 1.12...1.16, redeploy istio-gateway.  Worked
* deploy istio 1.11, `juju refresh istio-pilot` to 1.12 and **forget to remove** istio-gateway beforehand, eventually remove istio-gateway when the refresh gets stuck.  redeploy istio-gateway after the refresh completes.  Worked

**Comment by i-chvets** [comment]
I will also paste same questions here:
- Should we remove istio-pilot:istio-pilot  istio-ingressgateway:istio-pilot relation prior to removal of istio-ingressgateway?
- What should we watch for after deleting istio-ingressgateway? Should application be completely cleared from the list or terminated status is enough to start upgrades?

**Comment by ca-scribner** [comment]
Removing the relation is ok but unnecessary.  Removing the application will result in the relation being removed too

After removing the gateway, just watch for the charm to fully leave the juju status. when it's gone from there, proceed. 

Atm there's no built in way to report the istio version after upgrade. The debug log for upgrade charm will mention what it's upgrading to, but that's all. One way would be for users to download istioctl and do 'istioctl version -i kubeflow'. We should make that easier though, maybe add an action to ask about the version?

**Review by DnPlas — APPROVED** [review]
Thanks @ca-scribner, LGTM. Please remember to bring these changes into main also.

**Pull request merged**
